name: Build Trigger On Master
trigger:
  branches:
    include:
    - master
    
pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Run TwitchChatDownloader.UnitTests'
  inputs:
    command: test
    projects: 'TwitchChatDownloader.UnitTests\TwitchChatDownloader.UnitTests.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Run TwitchChatDownloader.IntegrationTests'
  inputs:
    command: test
    projects: 'TwitchChatDownloader.IntegrationTests\TwitchChatDownloader.IntegrationTests.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build TwitchChatDownloader'
  inputs:
    command: publish
    projects: 'TwitchChatDownloader\TwitchChatDownloader.csproj'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)\TwitchChatDownloader'

- task: PublishPipelineArtifact@0
  displayName: 'Publish TwitchChatDownloader Artifact'
  inputs:
    artifactName: 'TwitchChatDownloader'
    targetPath: $(Build.ArtifactStagingDirectory)\TwitchChatDownloader
