name: Build Trigger On Master
trigger:
  branches:
    include:
    - master
    
pool:
  vmImage: 'vs2017-win2016'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Run TwitchChatDownloader.UnitTests'
  inputs:
    command: test
    projects: 'TwitchChatDownloader.UnitTests\TwitchChatDownloader.UnitTests.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Run TwitchChatDownloader.IntegrationTests'
  inputs:
    command: test
    projects: 'TwitchChatDownloader.IntegrationTests\TwitchChatDownloader.IntegrationTests.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build TwitchChatDownloader'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'TwitchChatDownloader\TwitchChatDownloader.csproj'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)\TwitchChatDownloader'

- task: GitHubRelease@0
  displayName: 'Publish release to GitHub'
  inputs:
    gitHubConnection: 'DumpsterDoofus'
    repositoryName: 'Twitch-Chat-Downloader'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'auto'
    assets: '$(Build.ArtifactStagingDirectory)/*'
